version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: museum-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: RootPass#2025
      MYSQL_DATABASE: museum_db
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_estonian_ci
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d  # Mounts the SQL init script

volumes:
  mysql_data:
